cassandra.contact-point=127.0.0.1
cassandra.port=9042
cassandra.local-datacenter=datacenter1
cassandra.keyspace=oil_lab

cassandra.flyway-url=jdbc:cassandra://127.0.0.1:9042?localdatacenter=datacenter1