elasticsearch.scheme=http
elasticsearch.host=localhost
elasticsearch.port=9200

elasticsearch.username=
elasticsearch.password=

elasticsearch.index.fields=fields
elasticsearch.index.wells=wells
elasticsearch.index.productions=productions

elasticsearch.recreate-indices=true