services:
  clickhouse:
    image: clickhouse/clickhouse-server:25.8
    container_name: local-clickhouse
    restart: "no"
    ports:
      - "8123:8123"
      - "9000:9000"
    environment:
      CLICKHOUSE_DB: oil_lab
      CLICKHOUSE_USER: lab_user
      CLICKHOUSE_PASSWORD: 12345
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - clickhouse_logs:/var/log/clickhouse-server
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

volumes:
  clickhouse_data:
  clickhouse_logs: