services:
  cassandra:
    image: cassandra:5.0
    container_name: local-cassandra
    restart: "no"
    ports:
      - "9042:9042"
    environment:
      CASSANDRA_CLUSTER_NAME: "OilLabCluster"
      CASSANDRA_DC: "datacenter1"
      CASSANDRA_RACK: "rack1"
      CASSANDRA_ENDPOINT_SNITCH: "GossipingPropertyFileSnitch"
    volumes:
      - cassandra_data:/var/lib/cassandra
    healthcheck:
      test: ["CMD-SHELL", "cqlsh -e 'DESCRIBE KEYSPACES' localhost 9042"]
      interval: 20s
      timeout: 10s
      retries: 10
      start_period: 60s

volumes:
  cassandra_data: